# https://docs.github.com/en/actions/guides
# CI name , it will display on github's action page menu
name: SpringBoot norepeat
# trigger on which this CI should be run
on: # push operation is operate
  push:
    # here since my repository branch is named `main` , you should follow your own repository like `master`
    branches: [norepeat_springboot]
# CI enviroment settings
env:
  STATE_RELEASE_VERSION: "1.0.3" # version
  TAG_NAME: "norepeat_springboot" #tag 只能小写开头
  java-version: "11"
jobs:
  build:
    name: 构建,发布
    #runs-on: ubuntu-latest # use latest ubuntu to run the job
    runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ ubuntu-18.04, macos-10.15,macos-11 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java-version }}
      - name: Build with Maven
        run:
           mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: show files
        run: ls -a
      - name: Output Docker info
        run: docker info
      - name: Output Docker info
        run: docker buildx ls
      - name: Sets build date
        run: echo "BUILD_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #版本号第一位不允许空格
      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: "includeno/${{ env.TAG_NAME }}:latest,includeno/${{ env.TAG_NAME }}:${{ env.STATE_RELEASE_VERSION }}"
          push: true
      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "success"
      #https://github.com/8398a7/action-slack
      - name: Slack Nofitication
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.